name: Build and Deploy
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.85 # Используем последнюю поддерживаемую версию Rust для SP1
          target: wasm32-unknown-unknown
          components: rustfmt, clippy
          override: true
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Clear Rust Cache
        run: cargo clean
      - name: Set RUST_BACKTRACE
        run: echo "RUST_BACKTRACE=1" >> $GITHUB_ENV
      - name: Create target directory
        run: mkdir -p target
      - name: Set CARGO_TARGET_DIR
        run: echo "CARGO_TARGET_DIR=target" >> $GITHUB_ENV
      - name: Install SP1 CLI
        run: |
          cargo install --git https://github.com/succinctlabs/sp1.git --tag v4.1.2 --locked sp1-cli
      - name: Build Tetris Program ELF
        run: |
          cd example/fibonacci-program
          cargo prove build --locked
      - name: Build Verifier WASM
        run: |
          cd verifier
          cargo build --release --target wasm32-unknown-unknown --locked
          wasm-bindgen --target web --no-typescript --out-dir ../ target/wasm32-unknown-unknown/release/tetris-verifier.wasm
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
