name: Build and Deploy
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable # Устанавливаем стабильный Rust для начальной настройки
          target: wasm32-unknown-unknown
          components: rustfmt, clippy
          override: true
      - name: Install SP1 Toolchain with sp1up
        run: |
          curl -L https://sp1up.succinct.xyz | bash
          source ~/.bashrc || source ~/.zshrc # Активируем sp1up
          sp1up
      - name: Verify SP1 Installation
        run: |
          cargo prove --version
          RUSTUP_TOOLCHAIN=succinct cargo --version
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Clear Rust Cache
        run: cargo clean
      - name: Set RUST_BACKTRACE
        run: echo "RUST_BACKTRACE=full" >> $GITHUB_ENV
      - name: Create target directory
        run: mkdir -p target
      - name: Set CARGO_TARGET_DIR
        run: echo "CARGO_TARGET_DIR=target" >> $GITHUB_ENV
      - name: Set RUSTUP_TOOLCHAIN
        run: echo "RUSTUP_TOOLCHAIN=succinct" >> $GITHUB_ENV
      - name: Build Tetris Program ELF
        run: |
          cd example/fibonacci-program
          cargo prove build --locked
      - name: Build Verifier WASM
        run: |
          cd verifier
          cargo build --release --target wasm32-unknown-unknown --locked
          wasm-bindgen --target web --no-typescript --out-dir ../ target/wasm32-unknown-unknown/release/tetris-verifier.wasm
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
